### ISSUE TITLE
Fix the delay when clicking to jump 

### ISSUE THREAD

**Issue by Muriilow** [Muriilow/Capivara#6]
### What's happennng 

The game right now have a very notorius bug, when pressing the device and pressing it again very fast at a second time the jump wil not be registered, only on the first action, so the game ignore the action and the capybara doesn't jump. Here is some things that i already notice 
- Its only happen on my mobile service; 
- Neither using gestures or mouse events work;
- I think doing the action in the step event makes less buggy;
- Even when checking if it was pressed at every frame the game just doesn't make the action;

**Comment by Muriilo779** [comment]
### 18/06/23 I tested the game at my mother smartphone, and doesn't seem to have this bug, for some reason only happens on mine cellphone, so now I know its not my code, it can be now: 
-  My android version, and so some problem with android studio when I was creating the assets necessary;
- My touch screen, manly because its cracked;
- Compatibility issue with gamemaker
#### I need to test more, my fear is in the last option, because it cannot be corrected

**Comment by Muriilo779** [comment]
Update on the error 
The error occurred because when clicking twice in a row, the game understands it as a double click (equivalent to the right mouse button). It is possible to disable this recognition only using a single function. Since my code is based on the left click of the mouse (equivalent to a single click on the cell phone) when clicking 2 times in a short period of time the game recognized this as a right click and the jump action did not occur. 
I just use the function below in the object who control the game 
![image](https://github.com/Muriilo779/Capivara/assets/87148235/32a0be08-7027-4244-9412-f956e479a994)
